version: "3.8"
services:
  app:
    container_name: metabase-app
    image: metabase/metabase:v0.49.11
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      TZ: "Asia/Jakarta"
      JAVA_TIMEZONE: "Asia/Jakarta"
      MB_DB_TYPE: "postgres"
      MB_DB_HOST: "db"
      MB_DB_PORT: 5432
      MB_DB_DBNAME: "metabase"
      MB_DB_USER: "metabase"
      MB_DB_PASS: "metabase"
    volumes:
      - /to/host/path/metabase/app/metabase-data:/metabase-data
      - /to/host/path/metabase/app/plugins:/plugins
    depends_on:
      - db

  db:
    container_name: metabase-db
    image: postgres:16.3-alpine
    restart: unless-stopped
    environment:
      TZ: "Asia/Jakarta"
      POSTGRES_DB: "metabase"
      POSTGRES_USER: "metabase"
      POSTGRES_PASSWORD: "metabase"
    volumes:
      - /to/host/path/metabase/db/data:/var/lib/postgresql/data

networks:
  default:
    external: true
    name: dev_net2
