version: "3.8"
services:
  db:
    container_name: postgresql
    image: "postgres:16.3-alpine"
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      TZ: "Asia/Jakarta"
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Password1234"
    volumes:
      - /to/host/path/postgresql/data:/var/lib/postgresql/data

networks:
  default:
    external: true
    name: dev_net1
